// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Company struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Location string `json:"location"`
}

type Job struct {
	ID      string   `json:"id"`
	Title   string   `json:"title"`
	Desc    string   `json:"desc"`
	Company *Company `json:"company"`
}

type NewCompany struct {
	Name     string `json:"name"`
	Location string `json:"location"`
}

type NewJob struct {
	Companyid string `json:"companyid"`
	Title     string `json:"title"`
	Desc      string `json:"desc"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
